apiVersion: v1
kind: Service
metadata:
  name: id-generator
spec:
  selector:
    app: id-generator
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
